/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BEColoniedeFourmis;


public class App {

    public static void main(String[] args)   {
        MyWindow wind = new MyWindow();
    }
}
